disabled_rules:
  - line_length
  
opt_in_rules:
  - empty_count
  - first_where
  - trailing_whitespace
  - identifier_name
  

included:
  - DigioStore

excluded:
  - Pods
  - Carthage
  - fastlane
  - DigioStore/Generated

line_length: 120

