disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name
  
opt_in_rules:
  - empty_count
  - first_where

included:
  - DigioStore

excluded:
  - Pods
  - Carthage
  - fastlane
  - DigioStore/Generated

line_length: 120

